spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?user=postgres.mgptkrvuirdpqlbcotdi&password=gQvklPlpi02afeHo


server:
  port: 8080
  max-http-request-header-size: 1MB

logging:
  file:
    name: logs/homolog/application_dev.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.nexcodelab: INFO
    org.hibernate: ERROR

jwt:
  secret: agendaclinicaser
  expiration: 2592000000 # 30 days or 2592000000 milisecs